# Generated by Django 3.2.4 on 2021-06-04 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import renting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRentalHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Greater Accra Region', 'Greater Accra Region'), ('Ashanti Region', 'Ashanti Region'), ('Western North Region', 'Western North Region'), ('Western Region', 'Western Region'), ('Volta Region', 'Volta Region'), ('Eastern Region', 'Eastern Region'), ('Upper East Region', 'Upper East Region'), ('North East Region', 'North East Region'), ('Ahafo Region', 'Ahafo Region'), ('Bono Region', 'Bono Region'), ('Savannah Region', 'Savannah Region'), ('Bono East Region', 'Bono East Region'), ('Oti Region', 'Oti Region'), ('Northern Region', 'Northern Region'), ('Upper West Region', 'Upper West Region'), ('Central Region', 'Central Region')], max_length=100)),
                ('street_address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('zipcode', models.CharField(max_length=12)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('in_date', models.DateField()),
                ('out_date', models.DateField()),
                ('rent', models.PositiveIntegerField(default=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_allowed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('smoking_allowed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('musical_instrument', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('nrh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.newrentalhouse')),
            ],
        ),
        migrations.CreateModel(
            name='PreferredTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=1)),
                ('couple_friendly', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('bachelor_allowed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('nrh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.newrentalhouse')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to=renting.models.house_images)),
                ('nrh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renting.newrentalhouse')),
            ],
        ),
        migrations.CreateModel(
            name='HouseHas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom', models.CharField(choices=[('zero', 0), ('one', 1), ('two', 2), ('three', 3), ('three_plus', 4)], max_length=11)),
                ('kitchen', models.CharField(choices=[('Pr', 'Private'), ('Sh', 'Shared'), ('No', 'Not Available')], max_length=2)),
                ('bathroom', models.CharField(choices=[('Pr', 'Private'), ('Sh', 'Shared'), ('No', 'Not Available')], max_length=2)),
                ('living_room', models.CharField(choices=[('Pr', 'Private'), ('Sh', 'Shared'), ('No', 'Not Available')], max_length=2)),
                ('toilet', models.CharField(choices=[('Pr', 'Private'), ('Sh', 'Shared'), ('No', 'Not Available')], max_length=2)),
                ('balcony', models.CharField(choices=[('Pr', 'Private'), ('Sh', 'Shared'), ('No', 'Not Available')], max_length=2)),
                ('parking', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2)),
                ('nrh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.newrentalhouse')),
            ],
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('closet', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('tv', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('washing_machine', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('dryer', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('dishwasher', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('kitchenware', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('wifi', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('heating', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('air_conditioning', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('bed', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('furnished', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('nrh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='renting.newrentalhouse')),
            ],
        ),
    ]
