# Generated by Django 3.2.4 on 2021-06-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='air_conditioning',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='closet',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='desk',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='dishwasher',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='dryer',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='kitchenware',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='tv',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='washing_machine',
        ),
        migrations.RemoveField(
            model_name='amenities',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='newrentalhouse',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='preferredtenant',
            name='bachelor_allowed',
        ),
        migrations.RemoveField(
            model_name='preferredtenant',
            name='couple_friendly',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='animal_allowed',
        ),
    ]
