# Generated by Django 3.2.4 on 2021-07-19 14:22

from django.db import migrations, models
import renting.models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='images',
            field=models.FileField(blank=True, upload_to=renting.models.house_images),
        ),
    ]
