# Generated by Django 3.2.4 on 2021-07-26 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_househas_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houseimages',
            name='images',
        ),
    ]
