# Generated by Django 3.2.4 on 2021-07-01 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_auto_20210611_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newrentalhouse',
            name='in_date',
        ),
        migrations.RemoveField(
            model_name='newrentalhouse',
            name='out_date',
        ),
    ]
