# Generated by Django 3.2.4 on 2021-07-19 14:37

from django.db import migrations, models
import renting.models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0002_alter_houseimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='images',
            field=models.ImageField(blank=True, upload_to=renting.models.house_images),
        ),
    ]
