# Generated by Django 3.2.4 on 2021-07-27 12:46

from django.db import migrations, models
import renting.models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0005_remove_houseimages_imagess'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseimages',
            name='imagess',
            field=models.FileField(blank=True, upload_to=renting.models.house_images),
        ),
    ]
