# Generated by Django 3.2.4 on 2021-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0006_houseimages_imagess'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrentalhouse',
            name='date_registered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
