# Generated by Django 3.2.4 on 2021-07-27 19:03

from django.db import migrations, models
import renting.models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0008_alter_houseimages_imagess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='imagess',
            field=models.ImageField(blank=True, default='img/default.jpg', upload_to=renting.models.house_images),
        ),
    ]
