# Generated by Django 3.2.4 on 2021-07-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0012_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
