# Generated by Django 3.2.4 on 2021-08-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0014_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredtenant',
            name='description',
            field=models.TextField(blank=True, default='Massa tempor nec feugiat nisl pretium. Egestas fringilla phasellus faucibus scelerisque eleifend donec Porta nibh venenatis cras sed felis eget velit aliquet. Neque volutpat ac tincidunt vitae semper quis lectus. Turpis in eu mi bibendum neque egestas congue quisque. Sed elementum tempus egestas sed sed risus pretium quam. Dignissim sodales ut eu sem. Nibh mauris cursus mattis molesteeiaculis at erat pellentesque. Id interdum velit laoreet id donec', null=True),
        ),
    ]
