# Generated by Django 3.2.4 on 2021-08-15 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_nrh'),
        ('renting', '0015_preferredtenant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrentalhouse',
            name='landlord_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
