# Generated by Django 3.2.4 on 2021-08-25 12:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0016_newrentalhouse_landlord_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseimages',
            name='imagess',
            field=cloudinary.models.CloudinaryField(blank=True, default='img/default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
