# Generated by Django 3.2.4 on 2021-07-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typed',
            name='student_hall',
            field=models.CharField(default='No Hall', max_length=100),
        ),
    ]
