# Generated by Django 3.2.4 on 2021-07-10 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='user_tye',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Student')], default='owner', max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='usertype',
            unique_together={('user', 'user_tye')},
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user_type',
        ),
    ]
