# Generated by Django 3.2.4 on 2021-07-15 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='phone_no',
            field=models.IntegerField(default='0000000000'),
        ),
        migrations.AddField(
            model_name='usertype',
            name='user_group',
            field=models.CharField(choices=[('student', 'student'), ('staff', 'staff'), ('landlord', 'landlord')], default='student', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='usertype',
            unique_together={('user', 'user_group')},
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user_type',
        ),
    ]
