# Generated by Django 3.2.4 on 2021-07-10 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20210710_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('landlord', 'Landlord')], default='owner', max_length=8),
        ),
        migrations.AlterUniqueTogether(
            name='usertype',
            unique_together={('user', 'user_type')},
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='user_tye',
        ),
    ]
