# Generated by Django 3.2.4 on 2021-07-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_typed_student_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typed',
            name='student_hall',
            field=models.CharField(blank=True, default='No Hall', max_length=100, null=True),
        ),
    ]
