# Generated by Django 3.2.4 on 2021-07-15 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20210715_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typed',
            unique_together={('user_id', 'user_group')},
        ),
    ]
