# Generated by Django 3.2.4 on 2021-08-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_nrh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=190)),
                ('email', models.EmailField(max_length=190)),
                ('message', models.TextField()),
            ],
        ),
    ]
