# Generated by Django 3.2.4 on 2021-07-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_usertype_typed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='typed',
            unique_together=set(),
        ),
    ]
