# Generated by Django 3.2.4 on 2021-07-15 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20210715_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typed',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ut', to=settings.AUTH_USER_MODEL),
        ),
    ]
