# Generated by Django 3.2.4 on 2021-07-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_typed_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typed',
            name='phone_no',
            field=models.IntegerField(default='9000000008', max_length=50, null=True),
        ),
    ]
