# Generated by Django 3.2.4 on 2021-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210815_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='landlord/profile_image/'),
        ),
    ]
