# Generated by Django 3.2.4 on 2021-07-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewStudent',
            fields=[
                ('index_number', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=10)),
                ('room_number', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('O', 'OTHERS')], max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField()),
                ('check_in', models.BooleanField()),
            ],
            options={
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='StudentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='media/StudentImages/%Y/%m/%d/')),
                ('new_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.newstudent')),
            ],
        ),
        migrations.CreateModel(
            name='PostAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_submitted', models.TimeField(auto_created=True, default=django.utils.timezone.now)),
                ('date_submitted', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('announcement_title', models.CharField(max_length=100)),
                ('announcement_body', models.TextField()),
                ('annou_user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='NewVisitor',
            fields=[
                ('vistor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visiting_status', models.CharField(choices=[('STUDENT', 'STUDENT'), ('NON-STUDENT', 'NON-STUDENT'), ('O', 'OTHERS')], max_length=100)),
                ('visitor_fullName', models.CharField(max_length=150)),
                ('visiting_room', models.CharField(max_length=20)),
                ('room_member_getting_visited', models.CharField(max_length=150)),
                ('visiting_mobile_number', models.CharField(max_length=30)),
                ('visiting_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visiting_date_time'],
            },
        ),
    ]
