# Generated by Django 3.2.4 on 2021-07-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postannouncement',
            name='hall',
            field=models.CharField(blank=True, default='akuafo_main', max_length=100, null=True),
        ),
    ]
