# Generated by Django 3.2.4 on 2021-07-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvisitor',
            name='visitor_index',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
