# Generated by Django 3.2.4 on 2021-07-18 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_newvisitor_visitor_in_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='st_index_number',
            field=models.CharField(default='10203040', max_length=50),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='newvisitor',
            name='visiting_status',
            field=models.CharField(max_length=100),
        ),
    ]
