# Generated by Django 3.2.4 on 2021-07-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_postannouncement_annou_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postannouncement',
            old_name='annou_user',
            new_name='annou_user_id',
        ),
    ]
