# Generated by Django 3.2.4 on 2021-07-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_newvisitor_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='hall',
            field=models.CharField(default='No Hall', max_length=50),
        ),
    ]
