# Generated by Django 3.2.4 on 2021-07-19 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_newvisitor_visitor_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_update', models.CharField(max_length=20)),
                ('visitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.newvisitor')),
            ],
        ),
    ]
