# Generated by Django 3.2.4 on 2021-07-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_rename_annou_user_postannouncement_annou_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postannouncement',
            old_name='annou_user_id',
            new_name='annou_user',
        ),
    ]
