# Generated by Django 3.2.4 on 2021-08-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='images',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='media/StudentImages/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_image',
            field=models.ImageField(default='default.jpeg', upload_to='staff/profile_image/'),
        ),
    ]
