# Generated by Django 3.2.4 on 2021-07-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_annou_user_id_postannouncement_annou_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='check_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='date_registered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
