# Generated by Django 3.2.4 on 2021-08-25 12:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210818_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, default='default.jpeg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='default.jpeg', max_length=255, verbose_name='image'),
        ),
    ]
