# Generated by Django 3.2.4 on 2021-07-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20210716_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='images',
            field=models.ImageField(blank=True, upload_to='media/StudentImages/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('Graduate', 'Graduate')], max_length=50),
        ),
        migrations.DeleteModel(
            name='StudentImages',
        ),
    ]
