# Generated by Django 3.2.4 on 2021-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_updatevisitor_visitor_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='newvisitor',
            name='departed_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
