# Generated by Django 3.2.4 on 2021-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_newvisitor_departed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='index_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
