# Generated by Django 3.2.4 on 2021-07-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_newstudent_index_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newstudent',
            old_name='index_number',
            new_name='id',
        ),
    ]
