# Generated by Django 3.2.4 on 2021-07-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_rename_index_number_newstudent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='index_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
