# Generated by Django 3.2.4 on 2021-07-15 03:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewComplaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_index_number', models.CharField(max_length=20)),
                ('student_full_name', models.CharField(max_length=150)),
                ('student_room_number', models.CharField(max_length=10)),
                ('complaint_type', models.CharField(max_length=50)),
                ('complaint_description', models.TextField()),
                ('mobile_number', models.CharField(max_length=11)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('complaint_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
    ]
