# Generated by Django 3.2.4 on 2021-08-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(default='default.jpeg', upload_to='student/profile_image/'),
        ),
    ]
