# Generated by Django 3.2.4 on 2021-07-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_newcomplaint_student_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomplaint',
            name='student_hall',
            field=models.CharField(default='No_Hall', max_length=50),
        ),
    ]
