# Generated by Django 3.2.4 on 2021-08-25 12:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='default.jpeg', max_length=255, verbose_name='image'),
        ),
    ]
