# Generated by Django 3.2.4 on 2021-07-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_newcomplaint_student_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomplaint',
            name='student_hall',
            field=models.CharField(blank=True, default='No_Hall', max_length=50, null=True),
        ),
    ]
