# Generated by Django 3.2.4 on 2021-07-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomplaint',
            name='student_index_number',
            field=models.CharField(max_length=20),
        ),
    ]
