# Generated by Django 3.2.4 on 2021-07-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_newcomplaint_student_index_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='complaint_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintstatus',
            name='submitted_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracking.newcomplaint'),
        ),
    ]
