# Generated by Django 3.2.4 on 2021-07-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20210713_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintstatus',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.newcomplaint'),
        ),
    ]
