# Generated by Django 3.2.4 on 2021-07-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_complaintstatus_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcomplaint',
            name='complaint_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=20),
        ),
        migrations.DeleteModel(
            name='ComplaintStatus',
        ),
    ]
